### ISSUE TITLE
Problem in Destroy

### ISSUE THREAD

**Issue by Mrchiantos** [MultiCraft/MultiCraft#144]
I noticed a bug: when I destroy a node, it can happen that the one who is  y-1 is also destroyed.

This happens in a random way and seems to affect the nodes. I'm trying to see what would cause this

**Comment by Mrchiantos** [comment]
The bug comes from the combobox mod, I would look to fix it for multicraft.

**Comment by Mrchiantos** [comment]
i have found, i use 42 for digtime, this is very speed for multicraft.

i think use 100 or 200 for resolve my problem.

**Comment by MoNTE48** [comment]
Hmm, this should be the same for minetest/multicraft. 
Perhaps your game is created for MT 5.0 and in MT 5.0 some changes were made to the destroy speed in the engine itself, I did not look at it.

**Comment by Mrchiantos** [comment]
Use 200 digtime résolve problem. I hâve create this game in 0.4 .

**Comment by MoNTE48** [comment]
https://github.com/MultiCraft/MultiCraft/blob/master/games/default/files/player_api/init.lua#L36
Minetest_game used probably settings...
