### ISSUE TITLE
Problem Android.mk

### ISSUE THREAD

**Issue by elenamelchior** [MultiCraft/MultiCraft#148]
Hi ! in project i have this instruction 
"Debug build:
* Enter "build/android" subdirectory
* Execute "make"
* Answer the questions about where SDK and NDK are located on your filesystem
* Wait for build to finish
"
* android SDK (28+)
* android NDK (r17c)

But when open project i have this ERROR -MultiCraftmaster\MultiCraftmaster\build\android\native\jni\Android.mk

Help me pls resolve this problem, Thank you!

**Comment by MoNTE48** [comment]
The instruction is out of date. Build with _make_ is no longer supported.
