### ISSUE TITLE
Compatibility with minetest 5.0

### ISSUE THREAD

**Issue by Rafi594** [MultiCraft/MultiCraft#151]
Hello

Is Multicraft will be compatible with Minetest 5.0 someday ?

**Comment by MoNTE48** [comment]
Hello.
Depending on what you mean by compatibility.
MultiCraft is developed as a third-party game and compatibility with third-party mods or subgames is not guaranteed and is not the goal.
We fully support Minetest 0.4 servers, Minetest 0.4 also supports MultiCraft servers, but not fully
