### ISSUE TITLE
Android 9/10: Android build doesn’t work

### ISSUE THREAD

**Issue by jbelyaev** [MultiCraft/MultiCraft#152]
Hello,
Thank you for your effort!

I’ve tried to compile Android version and see that it doesn’t work. Have you seen this before?

![D9336314-0BDA-4013-9DCB-58173A1DDC18](https://user-images.githubusercontent.com/13788041/71297812-af803f80-238d-11ea-8584-01384bcc8744.jpeg)

**Comment by yube-sitecore** [comment]
@MoNTE48, could you assist with this one, please.
Is it a known problem?

**Comment by MoNTE48** [comment]
You must manually prepare the assets. Gradle does not do this automatically yet.

**Comment by yube-sitecore** [comment]
Thank you @MoNTE48 ,
I will look into it. I appreciate your effort.

**Comment by MoNTE48** [comment]
Just execute Start.sh before starting the build.

**Comment by jbelyaev** [comment]
Hello @MoNTE48,
Thank you for the suggestion, but I also did it.

Assets for 'debug' apk looks like this:
![image](https://user-images.githubusercontent.com/13788041/71641849-ea964300-2caa-11ea-9bc0-c3015000f864.png)

I used the latest Android SDK and tried to use different NDK versions (r17c or 20.1.5948944) - no problems during the build time. 

I've attached the 'debug' APK. Could you have a look, please, if it's possible.

[app-arm64-v8a-debug.zip](https://github.com/MultiCraft/MultiCraft/files/4014101/app-arm64-v8a-debug.zip)

**Comment by jbelyaev** [comment]
@MoNTE48, I found the root cause - missing cache.zip file. The problem is not actual for me.

Thank you.

**Comment by MoNTE48** [comment]
Anyway, thanks for reporting the bug! I will fix this later. Have a nice day!
