### ISSUE TITLE
User restrictions and rules

### ISSUE THREAD

**Issue by cocoeeyore** [MultiCraft/MultiCraft#153]
Hello, I am a user of your app, MultiCraft. I have noticed that your app is catered to users 9+. While I was using your app, I came across some people making homophobic remarks and telling people to “go kill themselves” among many other things. Unfortunately, I was not able to find any way to contact people involved in the making of this app aside from right here, and I was also unable to get any information about the app’s rules. Could I please get some information about what restrictions are put on users and their actions? Would the people that work on this app do anything about this problem? Thank you for your time.

**Comment by MoNTE48** [comment]
Hello. GitHub is only for reporting bugs. Support email is available on the application page.
