### ISSUE TITLE
Inventory doesn't work

### ISSUE THREAD

**Issue by strannik-j** [MultiCraft/MultiCraft#158]
Good afternoon!
I tried compiling versions 1.9.3 and 1.6 on different Linux versions (Ubuntu 18.04 x64 and Manjaro x64), and each compiled version had the same bug: the inventory doesn't work. When you click the " I " button, the screen darkens slightly, but the inventory itself does not appear. The lower panel with quick access works fine.

When connecting to other servers, the inventory works normally. But if you run the server on the compiled version, the inventory doesn't work even on the official android client.

![image](https://user-images.githubusercontent.com/1291326/83343595-2b02f700-a305-11ea-8036-a1ba92fa04b4.png)

**Comment by MoNTE48** [comment]
MultiCraft does not officially support Desktop and the issue is not related to the MultiCraft engine.  The inventory mod must be installed separately.

**Comment by strannik-j** [comment]
Wait, I don't understand something: multicraft is not an opensource? You said that all the game code is open, but there is no inventory module! There is not even a name or address to get it from.

**Comment by MoNTE48** [comment]
All engine code is completely open sourced if we talk about it. C++ src, Lua builtin, Java Android part.
This repository contains all MultiCraft Engine source code.

**Comment by strannik-j** [comment]
Correct me if I'm wrong: I don't have any way to run a game identical to MultiCraft on my server?

**Comment by MoNTE48** [comment]
1) This question really does not apply to Engine (this repository) and should be asked elsewhere.
2) Short answer: right now no. Long answer: we are working on it. Users will be able to create their servers based on MultiCraft_game in the future.
