### ISSUE TITLE
MultiCraft can not continue without a valid font. Please correct the 'font_path' setting or install the font file in the proper location

### ISSUE THREAD

**Issue by Spyspyspy** [MultiCraft/MultiCraft#159]
Hello, I've built it for osx, and trying to launch xcode project, and get this

MultiCraft can not continue without a valid font. Please correct the 'font_path' setting or install the font file in the proper location

**Comment by MoNTE48** [comment]
Hello. OSX is not officially supported and has never been tested. MultiCraft is officially developed and tested only for Android and iOS.
