### ISSUE TITLE
iOS game

### ISSUE THREAD

**Issue by h3dgar** [MultiCraft/MultiCraft#161]
Main menu:
When type words in iOS iPad it’s soo laggy.
New host server, could you allow us to create our generated world.
Settings feature for androids and iOS

Game:
Movement buttons - can they be floating and don’t stay at one place?

Server (new)
Switching  between creative and survival inventory stay as creative not functional at all (have to rejoin server)

**Comment by MoNTE48** [comment]
Hello.
> When type words in iOS iPad it’s soo laggy.

known issue but no idea how to fix this yet. Try typing with a third-party keyboard.

> New host server, could you allow us to create our generated world.

The server is not created on your device. It is created on our hosting. Therefore, there is no way to transfer your existing singleplayer world to our hosting.

> Settings feature for androids and iOS

It is unlikely to be added. The game has excellent default settings for better performance and stability.

> Movement buttons - can they be floating and don’t stay at one place? 

Scheduled later this year.

> Switching between creative and survival inventory stay as creative not functional at all (have to rejoin server)

I checked it again and it works as it should. To change the mode, the server owner must stop the server, select another mode and restart it. It is not possible to change the mode for all players on the fly. Engine restrictions

**Comment by h3dgar** [comment]
> I checked it again and it works as it should. To change the mode, the server owner must stop the server, select another mode and restart it. It is not possible to change the mode for all players on the fly. Engine restrictions

Command /grantme creative then if I do /revoke (nickname) creative - equipment stay as it was on creative not fully functional

**Comment by MoNTE48** [comment]
Changing the mode for a player requires rejoin the player. A lot of things sets exactly at the moment the player join.

**Comment by h3dgar** [comment]
That understandable. Thanks for quick response.

**Comment by MoNTE48** [comment]
No problems. I will close it now, but feel free to write again if anything else.
Have a nice day. 👍
