### ISSUE TITLE
TNT not destroying

### ISSUE THREAD

**Issue by rafaelbreno** [MultiCraft/MultiCraft#164]
On iOS, in multiplayer world the TNT isn't destroying blocks around it, but it differs damage on around players and mobs.

**Comment by MoNTE48** [comment]
TNT is indeed disabled in multiplayer to prevent griffing.  TNT does not consider protected areas at the moment.

**Comment by XREALMYT** [comment]
> TNT is indeed disabled in multiplayer to prevent griffing.  TNT does not consider protected areas at the moment.

Hi MAKSIM I am a MultiCraft youtuber    I love MultiCraft so much. 😁👍
