### ISSUE TITLE
The SLIMEBLOCK

### ISSUE THREAD

**Issue by XREALMYT** [MultiCraft/MultiCraft#166]
The SLIMEBLOCK won't work I just go through it.  Please fix the bug,        Also I'm a big MultiCrafter. I'm a MultiCraft youtuber on YouTube  I'm always getting more people to play MultiCraft (cool game by the way 👍

**Comment by MoNTE48** [comment]
Issue will be fixed in the August update. Thank you.

**Comment by XREALMYT** [comment]
Thanks you are cool 😎
