### ISSUE TITLE
Self Hosted Server

### ISSUE THREAD

**Issue by tclela20** [MultiCraft/MultiCraft#176]
Hello,

I apologize if this is the wrong place, but is it possible to self host a server fully compatible with MultiCraft? We have several players mostly on iOS and Android (all family/friends), and a few PCs. We’ve setup a mine test server (Latest release), and the PC players and android players can access it. The one problem I found is that I cannot access it from iOS on multicraft. 

So is there an open source server build for MultiCraft?

**Comment by MoNTE48** [comment]
Hi.
MultiCraft is still based on Minetest 0.4. Unfortunately, the Minetest community did not care about its users and broke support for older versions with the transition to the new version (Minetest 0.5, renamed Minetest 5 later).
So, you can use **MultiCraft Engine** or the **Minetest _0.4.17_** for your purposes.

P.S. MultiCraft Engine is completely open source and you are in the right place.

**Comment by tclela20** [comment]
Awesome, thank you for that information! Looks like our problem is the minetest server we have running is on a .5 build vs .4. We will downgrade and give it a shot. Thank you for that information!
