### ISSUE TITLE
Creating world for just my kids

### ISSUE THREAD

**Issue by sicka7** [MultiCraft/MultiCraft#178]
Is there anyway I can get step-by-step instructions on creating a creative world that my kids can play and not have any other people join?

**Comment by MoNTE48** [comment]
We do not have any step-by-step instructions because everything is extremely simple.
The `Host Server` tab in the main menu of the game is what you need. There are only 2 buttons, it is impossible to get confused.

**Comment by sicka7** [comment]
So do I put it on the connect side or the host server side?

**Comment by sicka7** [comment]
Got it thank you!!!!!

**Comment by MoNTE48** [comment]
Well, one of the players creates Host. Tells another Invite code and they play together.
Only the player who knows the Invite code can join the server. If nobody plays on the server for some time, it turns off. Then the player who created it must go to the menu and start it again (big Power button).
