### ISSUE TITLE
Texture and shaders pack? And Custom Max Ram

### ISSUE THREAD

**Issue by Malaska678** [MultiCraft/MultiCraft#179]
:P i will add multicraft contrnt to my channel :)) Im obviously a minecraft youtuber.

**Comment by Malaska678** [comment]
I mean if we can allocate more ram then many lag problem can be fixed.

**Comment by Malaska678** [comment]
Why close maksim

**Comment by Malaska678** [comment]
Whould you add custom max ram

**Comment by MoNTE48** [comment]
It's impossible.

**Comment by Malaska678** [comment]
:( I have lag spikes when playing game for so long.

**Comment by artdeell** [comment]
> Whould you add custom max ram

It's impossible, because most programs in C can already use alll available RAM (except the protected pages, i/o  and other)
Lag spikes are due to memory leaks(maybe???), and require hard patching.

**Comment by MoNTE48** [comment]
I've backport several fixes from Minetest repo.
I wonder if they fix this issue partially.
