### ISSUE TITLE
Build ios fail with error  'ft2build.h' file not found in file CGUITTFont.h

### ISSUE THREAD

**Issue by takaaptech** [MultiCraft/MultiCraft#180]
Hi @MoNTE48 
I just trying to build ios client and I have this error, could you please take a look and help me? Thank you so much!

![image](https://user-images.githubusercontent.com/6276251/93023784-9dc98100-f61b-11ea-95b1-507aecbacc3d.png)

**Comment by MoNTE48** [comment]
Building the game is extremely simple and almost completely automated using a bash script. Study the source code and documentation to find the answer to your question.
