### ISSUE TITLE
Restoring hosting server on another device

### ISSUE THREAD

**Issue by AnnaAndreev** [MultiCraft/MultiCraft#182]
Hello , the server crashed, how do I restore it( start the server)?

**Comment by MoNTE48** [comment]
Hey. This is where the engine is supported. What server are we talking about?

**Comment by AnnaAndreev** [comment]
Invite code:3UWP5KJE 
Password : 150709
Admin name:Anna

**Comment by MoNTE48** [comment]
Ok I'll try to check it later

**Comment by AnnaAndreev** [comment]
Thank you

**Comment by MoNTE48** [comment]
@AnnaAndreev, your server worked for me with no issues. 
Can you screenshot crash and attach here? Thanks.

**Comment by AnnaAndreev** [comment]
![image](https://user-images.githubusercontent.com/72924670/96157759-605a5b00-0f1b-11eb-986b-592b12038289.jpg)
It doesn’t see my server

**Comment by AnnaAndreev** [comment]
![image](https://user-images.githubusercontent.com/72924670/96158103-cfd04a80-0f1b-11eb-8cb0-cbd494cc7380.jpg)
I enter it again , and it returns a different one.

**Comment by MoNTE48** [comment]
Вы должны использовать ту же сеть интернет (с тем же IP адресом) для восстановления сервера. 
Мы работаем над восстановлением сервера по Invite Code и выпустим эту возможность в ближайшее время.

**Comment by AnnaAndreev** [comment]
То есть нужно ждать нового обновления ?

**Comment by artdeell** [comment]
> То есть нужно ждать нового обновления ?

Короче, либо ждать обновление, либо играть только на одной точке вайфай, как и в стандартном мобильном Майнкрафте

**Comment by MoNTE48** [comment]
Всё верно.
Восстановление сервера уже тестируется и будет доступно в ближайшее время.

**Comment by XREALM-YT** [comment]
> Всё верно.
> Восстановление сервера уже тестируется и будет доступно в ближайшее время. 

I cant recover or how do i do it? @MoNTE48

**Comment by MoNTE48** [comment]
@XREALM-YT, server recovering is already available on iOS to some users and will be available on Android in a few days.

**Comment by XREALM-YT** [comment]
> @XREALM-YT, server recovering is already available on iOS to some users and will be available on Android in a few days.

Ok boss ;)
![InShot_20201029_141221485.jpg](https://user-images.githubusercontent.com/73010605/97627560-285e1800-19f1-11eb-8bf0-a33fe82dd0fa.jpg)
@MoNTE48 i made it for you :) i love  Designing things:D pls reply if you love it

**Comment by XREALM-YT** [comment]
> @XREALM-YT, server recovering is already available on iOS to some users and will be available on Android in a few days.

How to use? I dont get it much idk russian too ;/ pls tell what is the way

**Comment by AnnaAndreev** [comment]
![Uploading 9E8D8D27-47E2-4BF7-89EB-8B11223D2CA2.png…]()
