### ISSUE TITLE
Auto build???

### ISSUE THREAD

**Issue by Malaska678** [MultiCraft/MultiCraft#183]

**Comment by MoNTE48** [comment]
What engine issue do you want to report? What is your OS?

**Comment by Malaska678** [comment]
I mean auto build source code. Then if we go to action section we will see those auto builds

**Comment by MoNTE48** [comment]
Will not be added for this version of the engine. Will be added after upgrading to the new version of Minetest Engine.

**Comment by Malaska678** [comment]
> Will not be added for this version of the engine. Will be added after upgrading to the new version of Minetest Engine.

Ok.
