### ISSUE TITLE
Compilation guide/pre-built bins will be available?

### ISSUE THREAD

**Issue by artdeell** [MultiCraft/MultiCraft#184]
I'd like to see a detailed guide about compiling MultiCraft, or, at least, pre-built binaries on GitHub.

**Comment by MoNTE48** [comment]
https://github.com/MultiCraft/MultiCraft/issues/183#issuecomment-711127318

**Comment by Malaska678** [comment]
> I'd like to see a detailed guide about compiling MultiCraft, or, at least, pre-built binaries on GitHub.

@artdeell Why your here hmmmm
