### ISSUE TITLE
Linux compartiblity

### ISSUE THREAD

**Issue by artdeell** [MultiCraft/MultiCraft#185]
If macOS is supported, why can't you add Linux build-ability?
I mean, you can build Windows release and play with Wine, but where's the native Linux compartiblity?

**Comment by MoNTE48** [comment]
Go to doc and read the assembly instructions.  MultiCraft is primarily written in Linux and for Linux.

**Comment by artdeell** [comment]
@MoNTE48 Where's the documentation then?
Website redirects to GH organization
GitHub Wiki does not exist for this repo

**Comment by artdeell** [comment]
@MoNTE48 And why are you closing issues that aren't solved? You just say "will be fixed in the next release".
Maybe you should close only after they become fixed?

**Comment by MoNTE48** [comment]
https://github.com/MultiCraft/MultiCraft/tree/master/doc#build

**Comment by artdeell** [comment]
@MoNTE48 And the last issue about Linux build: cURL-less build always fails. MultiCraft only builds with -CFLAGS=-DUSE_CURL=1

**Comment by MoNTE48** [comment]
Why build without CURL? Even the server list will not be available.
Is it difficult for you to install 1 package?

**Comment by artdeell** [comment]
Well, actually no
Anyway, after many attempts, I was forced to remove HTTP Lua bindings. It built, it starts, but does not enter the world. Will try something other tomorrow.
