### ISSUE TITLE
Can’t join any severs on multiplayer 

### ISSUE THREAD

**Issue by pokemon214** [MultiCraft/MultiCraft#199]
Hi I have a problem I can’t get on any of the multiplayer severs because it keeps saying invalid password when there is no password for it can you help me so I can play again and yes I deleted and reinstalled it but nothing happened it just says invalid password

**Comment by MoNTE48** [comment]
Hey. You are probably trying to connect under the already used name. Just try using a different name, add numbers, or whatever.

**Comment by pokemon214** [comment]
I have tried to use a different name but it told me that I have another account already but when I put it in it tells me invalid password still

**Comment by MoNTE48** [comment]
You're talking about the Multiplayer tab, right?

**Comment by pokemon214** [comment]
Yes I am

**Comment by MoNTE48** [comment]
Then please provide the name of the server and the name you are trying to use.
---
We have nothing to do with the servers, do not manage them and do not know what is wrong.

**Comment by pokemon214** [comment]
Ok
![5A5C5D13-CE3C-422F-AAE0-DA316ADFE8FC](https://user-images.githubusercontent.com/77754385/105280068-8e7cb600-5b6e-11eb-9ab2-3b8b7b07430f.jpeg)

**Comment by MoNTE48** [comment]
Of course this name is not free. You must use another or add numbers to it (ashaa2001)

**Comment by pokemon214** [comment]
How do I tame a fox in the game

**Comment by pokemon214** [comment]
And the bears

**Comment by MoNTE48** [comment]
There is no support for the game or aby server and we are not developing the game itself. Only engine. We do not know the answer to your question.
