### ISSUE TITLE
Where is the "Host Server" tab so I can join an invite code from my friend?

### ISSUE THREAD

**Issue by category-mirrory** [MultiCraft/MultiCraft#200]
Desktop:
![Desktop](https://user-images.githubusercontent.com/77921249/105629093-e3ebe800-5e38-11eb-8203-b69ac5f44ff6.png)
Phone:
![Phone](https://user-images.githubusercontent.com/77921249/105629094-e4847e80-5e38-11eb-9e49-af192040226c.png)

**Comment by MoNTE48** [comment]
This feature only for mobile players and not availabled for PC. There is no plan to allow PC players connect to this servers.
