### ISSUE TITLE
Hosting Server Issue

### ISSUE THREAD

**Issue by Matt1559** [MultiCraft/MultiCraft#204]
I have hosted a server to play with some friends, it was turned on this morning as friends had extra time and i just tried loading up the server myself and i get a error message saying "Cannot connect to server!" is there any solution to this without loosing anything?

**Comment by MoNTE48** [comment]
Hello. We've had a few weird failures in recent days. We are working on a fix.
Everything should be normal right now. We hope our players didn't have any data loss.

**Comment by Matt1559** [comment]
Hi, still having the same issue but thank you for the update. I will let you know if the issue gets resolved.

**Comment by MoNTE48** [comment]
I probably misunderstood your problem. Hosting is now fully operational.
Our technicians started investigating the causes of the incident, but they fixed all the problems about 10 hours ago.

**Comment by Matt1559** [comment]
![image](https://user-images.githubusercontent.com/79158158/108112867-a15fa900-708e-11eb-9d67-76872a88d0fa.png)

This is the screen I am getting whenever I try to turn on the server hosting or enter it myself.

**Comment by MoNTE48** [comment]
Check if you have access to the server list (in Multiplayer tab) and if you can connect to any of the MultiCraft servers.

**Comment by Matt1559** [comment]
Hi, yes I can connect to servers just not the one that I was hosting, it still doesn't want to turn on, I tried doing it on iPad as well when the iPhone didn't work and no luck with that either. Is there anything that can be done?

**Comment by MoNTE48** [comment]
Can you send me Invite Code, admin name and admin password to my email?
monte48@mail.ua

**Comment by Matt1559** [comment]
Just emailed you there, hopefully you can determine what the issue is, thank you in advance.

**Comment by MoNTE48** [comment]
I forgot to answer you yesterday. The problem is fixed, your server is fine. Once again I apologize for the inconvenience.

**Comment by Matt1559** [comment]
I noticed this this morning, thank you very much.
