### ISSUE TITLE
How will Convert Minecraft maps to Minetest worlds Function ?

### ISSUE THREAD

**Issue by Pantyhose-X** [MultiCraft/MultiCraft#205]
Convert Minecraft maps to Minetest worlds ?

[L map](https://www.planetminecraft.com/project/novigrad-timelapse-download/)

Reference
https://forum.minetest.net/viewtopic.php?f=12&t=13709&sid=64ab4a65e2791ce2b615a536130c7014

https://forum.minetest.net/viewtopic.php?f=14&t=14271&sid=3cd2c3fc6dedd9d79bdc4bf396b1b7d9

**Comment by MoNTE48** [comment]
Hello. If this is a feature request, then we are not interested in it.
You can try to do it yourself, but the MultiCraft developers are not interested in official support for such a feature.
