### ISSUE TITLE
Connection failure

### ISSUE THREAD

**Issue by ebru03** [MultiCraft/MultiCraft#206]
I have a server for me and my friends but we can't login anymore. It says "Connection failure: init packet not recognized by server." I don't even know what an init packet is, so I don't really think we did anything that has to do with it. We were building and mining and suddenly we were kicked out of the server. How can I solve this issue?

**Comment by MoNTE48** [comment]
Hello. I can't help you without even having basic information. Please explain the problem in more detail. Thank.

**Comment by ebru03** [comment]
> Hello. I can't help you without even having basic information. Please explain the problem in more detail. Thank. 

I have a server and it has an invite code ( N9IS1JV9 ) and a password, so only me and my friends can enter the server. There was never an issue but yesterday the server suddenly crashed and we couldn't enter anymore. Im gonna add a picture.
 ![image](https://user-images.githubusercontent.com/79644891/109196803-7830ce00-779c-11eb-8daf-bedd7965ba20.png)

Do you need further information?

**Comment by MoNTE48** [comment]
Please start the server and I will try to connect to it myself. Now I at least know that we are talking about hosting...

**Comment by ebru03** [comment]
> Please start the server and I will try to connect to it myself. Now I at least know that we are talking about hosting...

It's working again, thank you so much for taking care of this issue. (:
