### ISSUE TITLE
Keeps crashing.

### ISSUE THREAD

**Issue by mochagamer** [MultiCraft/MultiCraft#207]
Everytime I click join, it loads, but when it gets to 100%, it crashes out of the game.  Very annoyed.

**Comment by MoNTE48** [comment]
Hello. I can not help you. I do not know which OS, which application and where do you click "Join"? I bet there is no such button in our game!

**Comment by mochagamer** [comment]
> Hello. I can not help you. I do not know which OS, which application and where do you click "Join"? I bet there is no such button in our game!

![image](https://user-images.githubusercontent.com/79729251/109396431-5fccca80-78e6-11eb-8125-94d46204736b.png)

When I click play, it loads, but as soon as it reaches 100%, it closes the game.  I am using Macbook air, i've tried deleting the app and redownloading it.  Please fix the issue.  Thank you.

**Comment by MoNTE48** [comment]
More information please. macOS version, the year of the Macbook. The MacBook Air has been in production for over 10 years and has dozens of models. I can't help you with just one screenshot!

**Comment by mochagamer** [comment]
> More information please. macOS version, the year of the Macbook. The MacBook Air has been in production for over 10 years and has dozens of models. I can't help you with just one screenshot!

Do you need a translation?  I press play, and it loads, right?  The loading screen gets to 100%, and then it quits the game unexpectedly. My macbook is from 2020, i just got it last year.  It is the 13 inch one

**Comment by MoNTE48** [comment]
I don't need a translation. I was just trying to figure out if your MacBook Air is a 2008 model or a 2021 model on an Apple M1! I'm not a telepathic person.
I want to believe that you are using macOS Catalina 10.15 or Big Sur 11?
Try disabling shaders in the Settings section and tell me if that fixed the problem.

**Comment by MoNTE48** [comment]
I believe this issue has been resolved.
If not, please write and I will open it again.
