### ISSUE TITLE
Help me with hack clients, please!

### ISSUE THREAD

**Issue by animetrom** [MultiCraft/MultiCraft#48]
## Problem

Meeting, currently several hack clients that allow a lot on servers.
Immense help help to see a way to prevent users from entering the server with these clients.
Help me please!

## Solutions

I found a name server "Survivalgo", which managed to prevent, in some way, to enter with hack clients in the game and only allow original.
Whenever someone tries to enter some client cheating, it appears the message "This client is not supported".

## Alternatives

I wanted some shape, configuration, mod whatever to prevent them from using it because I have a server and I need more than something like that.

## Additional context

I beg for help! The "Survivalgo" name server uses MULTICRAFT2 as client-server.

**Comment by r1bnc** [comment]
This can be accomplished by using a mod that checks client versions and allow only specified clients. Tbh nothing beats active moderation of servers.

**Comment by mightyjoe781** [comment]
Look into a mod called as `beowulf` mod by mt-mods.

**Comment by fluxionary** [comment]
see various resources at https://forum.minetest.net/viewtopic.php?f=3&t=27465

i managed to get the creator of the dragonfire client to put the string "dragonfire" in the version string, which you can access via the lua API:

https://github.com/MultiCraft/MultiCraft/blob/17ebe562a3a7c8c79a9fc7a4346c90bc642ba41a/doc/lua_api.txt#L4515-L4541

you can write a mod that checks the version string when a player joins, and kicks them if they've got one you dislike.
