### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by acheron123** [MultiCraft/MultiCraft#59]
## Problem
Currently, MultiCraft does not have official release for Linux platform. However, Minetest already supports all major desktop platforms including Linux; it should be fairly easy to get support for Linux therefore. Would you consider supporting MultiCraft on Linux? Thanks!

## Solutions
The official website should contain an official binary for Linux too.

## Alternatives
I have compiled the project from source, but only the development version is available for compilation. Is it possible to join MultiCraft custom (hosted) server from Minetest? If yes, that would be enough, since Minetest does indeed support Linux just fine.

**Comment by MoNTE48** [comment]
Linux is supported (although not thoroughly tested) but we do not offer any binaries for it. We suggest that you can easily compile the game yourself using the source code and instructions in the README.


> Is it possible to join MultiCraft custom (hosted) server from Minetest? 
Sure! Minetest and MultiCraft are fully compatible.

**Comment by r1bnc** [comment]
He might be referring to the Multicraft app that allows you to join via Invite codes.

**Comment by fluxionary** [comment]
> I have compiled the project from source, but only the development version is available for compilation.

you can download the source of specific releases here: https://github.com/MultiCraft/MultiCraft/tags
