### ISSUE TITLE
Compare with MineTest

### ISSUE THREAD

**Issue by mk-pmb** [MultiCraft/MultiCraft#6]
Hi! Could you please add some kind of overview of the idea behind this project, maybe a comparison with MineTest?

**Comment by MoNTE48** [comment]
Hello.
I'm not too eloquent, but MultiCraft is probably an attempt to develop a "ready-made" game that has a nice interface and doesn't require the player to have any development skills when he just wants to play.
An attempt to create a more stable engine that addresses various stability and performance issues.
An attempt to create a better server that deals with compatibility issues for administrators.
An attempt to create a more cohesive community in which content creators have priority for engine developers, and not vice versa.
And also have a nice time coding and hacking the engine. 🙂

**Comment by testman42** [comment]
Maybe add this to README.mdf

**Comment by Festus1965** [comment]
> I'm not too eloquent, but MultiCraft is probably an attempt to develop a "ready-made" game that has a nice interface and doesn't require the player to have any development skills when he just wants to play.
This is funny, when I started play minetest, I also had no idea from the engine or the mods ... and did't have even any practice from Minecraft. I just used my brain ! - I just learn by try and some logic and looking other builds, and listen in the chat about written solutions. So Minetest can still be played without knowledge of dev skills, even my further 6 years old daughter got it. - So I absolutely don't understand this point.
What I know about (and have seen that on my server) MultiCraft users is, that they behave like in MineCraft: no any thoughts about others builds and areas.
"Just wanna play' is the same ... but to have some basic respect to other players is another.

**Comment by MoNTE48** [comment]
Dear Thomas. I bet that the development of the source code and the actual behavior of the players on someone's servers using this source code are not related things.
I'm not interested in servers, in the Minetest community, etc. I'm just doing what I'm interested in.
