### ISSUE TITLE
error when creating world

### ISSUE THREAD

**Issue by ACE-Devs** [MultiCraft/MultiCraft#64]
when I try to make a world it says: `Failed to initialize world: Failed to update config`
Please give instructions of how to fix.
Thank you

**Comment by MoNTE48** [comment]
Make sure you have free space on your disk and that the compiled game has write rights to files, depending on the platform.

**Comment by ACE-Devs** [comment]
thanks!!! that was very helpful

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
