### ISSUE TITLE
Drowning while standing in doors using the official Minetest client

### ISSUE THREAD

**Issue by stormchaser3000** [MultiCraft/MultiCraft#65]
The server seems to be running Multicraft 2.0.0 and my Minetest client is 5.5.1

##### OS / Hardware

Operating system: All operating systems
CPU: AMD Ryzen 3 (I can't remember the specific model)

##### Summary
I am sure that Multicraft<->Minetest client-server protocol compatibility isn't necessarily high on your list, but I figured I would mention it in-case you get a chance to look into it. When joining the SurvivalGo server from Minetest 5.5.1, I start drowning while standing in doorways. This apparently doesn't happen on the Multicraft client.

##### Steps to reproduce
Download Minetest 5.5.1 and log into SurvivalGo or start a server using multicraft's server executable and join it using the latest stable minetest client, then stand in a doorway. You should start drowning.

**Comment by luk3yx** [comment]
I don't think this bug is limited to Minetest clients, I just tested on a local MultiCraft server with minetest_game and I can drown inside of doors.

**Comment by IrrlichtMt4** [comment]
Will test soon.
