### ISSUE TITLE
How to mod MultiCraft?

### ISSUE THREAD

**Issue by dummy12354** [MultiCraft/MultiCraft#7]
I am sure Minetest mods (not all but some) can be used in MultiCraft as in the source code there is a file that says to put mods in that folder. But the problem is when you install MultiCraft, there is no folder to put the mods.

So please tell me how to mod MultiCraft.

**Comment by jcq333** [comment]
Make the folder

**Comment by git512** [comment]
Just making a mods folder in your main multicraft folder (where bin,src and worlds are) and putting them in there works great. Also the find more mods/mod installer feature is awesome.

**Comment by mightyjoe781** [comment]
you have 2 options
1. Make the `mods` folder in the main source tree i.e. inside (`~/MultiCraft2/mods/mycoolmod`)
or 
2. make `worldmods` folder inside your world folder (`~/MultiCraft2/worlds/worldname/worldmods/mycoolmod`)
Note : method 1 requires you to manually enable each mod into the world.conf file while method 2 require just a folder of mod to be copied there.
