### ISSUE TITLE
Last 2.0.2 isn't working

### ISSUE THREAD

**Issue by rudzik8** [MultiCraft/MultiCraft#89]
##### MultiCraft version
```
2.0.2 (commit 0810698)
```

##### OS / Hardware
Operating system: Windows 7 (x64)
CPU: AMD Athlon(tm) II X4 640 Processor (3.00 GHz)

##### Summary
MultiCraft isn't working anymore, installed it from Actions tab (as a MSVC artifact binary) and nothing. Just this.
Updated by replacing old `bin`, `builtin` and `client` folders with new ones (works almost always)

![image](https://user-images.githubusercontent.com/87843378/184060405-aad0a26c-23e1-4600-91f8-54a9f67fc5a1.png)

**Comment by zmv7** [comment]
> ##### MultiCraft version
> 
> ```
> 2.0.2 (commit 0810698)
> ```
> 
> ##### OS / Hardware
> 
> Operating system: Windows 7 (x64) CPU: AMD Athlon(tm) II X4 640 Processor (3.00 GHz)
> ##### Summary
> 
> MultiCraft isn't working anymore, installed it from Actions tab (as a MSVC artifact binary) and nothing. Just this. Updated by replacing old `bin`, `builtin` and `client` folders with new ones (works almost always)
> 
> ![image](https://user-images.githubusercontent.com/87843378/184060405-aad0a26c-23e1-4600-91f8-54a9f67fc5a1.png)

You can fix it by yourself, by replacing `builtin` directory with older one(from version 2.0.1)

**Comment by MoNTE48** [comment]
https://updates.multicraft.world/releases/windows/
